locales = [ "es",]
[[paths]]
reference = "templates/pages/philly-bike-action.pot"
l10n = "locales/{locale}/pages/philly-bike-action.po"
locales = [ "es",]

[[paths]]
reference = "templates/pages/philly-bike-action/test.pot"
l10n = "locales/{locale}/pages/philly-bike-action/test.po"
locales = [ "es",]

